#!/bin/bash
# FITWELL - FOOD DISPLAY FIX CHECKLIST
# Use this checklist to complete the implementation

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  FITWELL - FOOD DISPLAY FIX IMPLEMENTATION CHECKLIST          ║"
echo "║  Status: Code fixes ✅ COMPLETE | Migration ⏳ PENDING        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Code fixes status
echo "📝 CODE FIXES (✅ COMPLETED):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ src/types/index.ts"
echo "   - Enhanced FoodLog interface"
echo "   - Added foods?: Food property"
echo "   - Added optional fields: food_name, fdc_id, quantity_unit"
echo ""
echo "✅ src/hooks/useNutrition.ts"
echo "   - Added debug logging"
echo "   - Added error handling"
echo "   - Added data verification"
echo ""
echo "✅ src/screens/app/FoodLoggingScreen.tsx"
echo "   - Improved display fallback"
echo "   - Now shows 'Unnamed Food' if name is missing"
echo ""
echo "✅ database/MIGRATION_FOOD_LOGS.sql"
echo "   - Created ready-to-run SQL migration"
echo ""

# Database migration checklist
echo ""
echo "🗄️  DATABASE MIGRATION (⏳ NEEDS TO BE COMPLETED):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Go to Supabase Dashboard"
echo "  [ ] Navigate to: https://supabase.com/dashboard"
echo "  [ ] Select your project: fitwell"
echo ""
echo "Step 2: Open SQL Editor"
echo "  [ ] Click on 'SQL Editor' in the left menu"
echo "  [ ] Click 'New Query' button"
echo ""
echo "Step 3: Run Migration"
echo "  [ ] Open file: database/MIGRATION_FOOD_LOGS.sql"
echo "  [ ] Copy entire contents"
echo "  [ ] Paste into SQL Editor"
echo "  [ ] Click 'Run' button"
echo ""
echo "Step 4: Verify Migration"
echo "  [ ] Check that no errors appear"
echo "  [ ] Run verification query:"
echo "      SELECT column_name FROM information_schema.columns"
echo "      WHERE table_name = 'food_logs'"
echo "      AND column_name IN ('fdc_id', 'food_name', 'quantity_unit');"
echo "  [ ] Should return 3 rows"
echo ""

# App testing checklist
echo ""
echo "🧪 APPLICATION TESTING (⏳ NEEDS TO BE COMPLETED):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Rebuild Application"
echo "  [ ] npm run build"
echo "  [ ] npm start"
echo ""
echo "Step 2: Open Food Logging Screen"
echo "  [ ] Launch the app"
echo "  [ ] Navigate to Food Logging screen"
echo "  [ ] Open browser console (F12)"
echo ""
echo "Step 3: Check Debug Logs"
echo "  [ ] Look for: [useNutrition] Fetching food logs for..."
echo "  [ ] Look for: [useNutrition] Fetched X food logs"
echo "  [ ] Look for: [useNutrition] Sample food log: {...}"
echo "  [ ] No error messages in console"
echo ""
echo "Step 4: Test Adding Food - Database Foods"
echo "  [ ] Click 'Add Food Item'"
echo "  [ ] Select 'Breakfast' from meal type"
echo "  [ ] Click 'App Foods' tab"
echo "  [ ] Select a category (e.g., Indian Foods)"
echo "  [ ] Select a food item"
echo "  [ ] Enter quantity (e.g., 100)"
echo "  [ ] Click 'Add' or 'Log' button"
echo "  [ ] Verify no error alert appears"
echo "  [ ] Verify food appears in Breakfast section"
echo "  [ ] Verify nutrition data displays (calories, protein, etc.)"
echo ""
echo "Step 5: Test Adding Food - USDA Foods"
echo "  [ ] Click 'Add Food Item'"
echo "  [ ] Select 'Lunch' from meal type"
echo "  [ ] Click 'USDA Search' tab"
echo "  [ ] Search for a food (e.g., 'rice')"
echo "  [ ] Wait for results"
echo "  [ ] Click on a result"
echo "  [ ] Enter quantity and unit"
echo "  [ ] Click 'Log Food'"
echo "  [ ] Verify success message appears"
echo "  [ ] Verify food appears in Lunch section"
echo ""
echo "Step 6: Test All Meal Types"
echo "  [ ] Add at least one food to each meal type:"
echo "      [ ] Breakfast"
echo "      [ ] Lunch"
echo "      [ ] Dinner"
echo "      [ ] Snack"
echo "  [ ] Verify all foods display in their correct sections"
echo "  [ ] Verify meal sections show correct meal type label"
echo ""

# Supabase verification
echo ""
echo "✅ SUPABASE VERIFICATION (⏳ NEEDS TO BE COMPLETED):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Check Table Structure"
echo "  [ ] In Supabase SQL Editor, run:"
echo "      SELECT column_name, data_type FROM information_schema.columns"
echo "      WHERE table_name = 'food_logs'"
echo "      ORDER BY ordinal_position;"
echo "  [ ] Verify these columns exist:"
echo "      - fdc_id (character varying)"
echo "      - food_name (character varying)"
echo "      - quantity_unit (character varying)"
echo ""
echo "Step 2: Check Data in food_logs Table"
echo "  [ ] In Supabase SQL Editor, run:"
echo "      SELECT * FROM food_logs LIMIT 5;"
echo "  [ ] Verify table has food entries with:"
echo "      [ ] food_id populated (for database foods)"
echo "      [ ] food_name populated (for USDA foods)"
echo "      [ ] quantity_unit set correctly (g, oz, cup, etc.)"
echo "      [ ] meal_type is lowercase (breakfast|lunch|dinner|snack)"
echo "      [ ] calories, protein_g, carbs_g, fats_g populated"
echo ""
echo "Step 3: Check Specific User Data"
echo "  [ ] Replace 'YOUR_USER_ID' with actual user ID"
echo "  [ ] Run:"
echo "      SELECT fl.id, fl.food_id, f.name, fl.meal_type,"
echo "             fl.date, fl.calories, fl.food_name, fl.fdc_id"
echo "      FROM food_logs fl"
echo "      LEFT JOIN foods f ON fl.food_id = f.id"
echo "      WHERE fl.user_id = 'YOUR_USER_ID'"
echo "      ORDER BY fl.created_at DESC LIMIT 10;"
echo "  [ ] Verify results show proper data structure"
echo ""

# Final verification
echo ""
echo "🎯 FINAL VERIFICATION (⏳ NEEDS TO BE COMPLETED):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ If all checks above pass, the fix is complete!"
echo ""
echo "  [ ] Code fixes applied"
echo "  [ ] Database migration executed"
echo "  [ ] App rebuilt and restarted"
echo "  [ ] Debug logs show in console"
echo "  [ ] Foods display in correct meal sections"
echo "  [ ] USDA foods can be logged"
echo "  [ ] Database has correct data structure"
echo "  [ ] No error messages in console or app"
echo ""

# Troubleshooting
echo ""
echo "❌ TROUBLESHOOTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Issue: No [useNutrition] logs in console"
echo "Solution:"
echo "  1. Check if userId and date are being passed correctly"
echo "  2. Verify user is authenticated"
echo "  3. Check React Query DevTools for 'foodLogs' query"
echo ""
echo "Issue: Foods added but not displaying"
echo "Solution:"
echo "  1. Check database - food_logs table"
echo "  2. Verify meal_type values are lowercase"
echo "  3. Check RLS policies allow access to user's data"
echo "  4. Look for error alerts in the app"
echo ""
echo "Issue: SQL migration failed"
echo "Solution:"
echo "  1. Check error message in Supabase dashboard"
echo "  2. Verify all SQL syntax is correct"
echo "  3. Check that table food_logs exists"
echo "  4. Try running statements one at a time"
echo ""
echo "Issue: Data not appearing in Supabase"
echo "Solution:"
echo "  1. Check food_logs table is empty initially (OK)"
echo "  2. Add food via app and wait ~5 seconds"
echo "  3. Refresh Supabase browser tab"
echo "  4. Check if pagination is hiding data"
echo ""

# Summary
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  IMPLEMENTATION CHECKLIST COMPLETE                            ║"
echo "║  Next: Follow the steps above in order                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
