#!/bin/bash
# FITWELL - FOOD DISPLAY FIX QUICK START
# This file contains all instructions needed to fix the food display issue

echo "🎯 FITWELL FOOD DISPLAY FIX"
echo "============================"
echo ""
echo "Issue: Food options not showing in breakfast, dinner, snacks"
echo "Status: ✅ Code fixes applied, migration ready"
echo ""
echo "📋 QUICK START (3 STEPS):"
echo ""
echo "STEP 1: Apply Database Migration"
echo "  1. Go to https://supabase.com/dashboard"
echo "  2. Navigate to your project"
echo "  3. Go to SQL Editor → New Query"
echo "  4. Open and run: database/MIGRATION_FOOD_LOGS.sql"
echo "  5. Click 'Run'"
echo ""
echo "STEP 2: Rebuild and Restart"
echo "  npm run build"
echo "  npm start"
echo ""
echo "STEP 3: Test"
echo "  1. Open FitWell app"
echo "  2. Go to Food Logging screen"
echo "  3. Check browser console for: [useNutrition] Fetching food logs..."
echo "  4. Add a food item"
echo "  5. Verify it appears in the correct meal section"
echo ""
echo "📚 DOCUMENTATION:"
echo "  - FOOD_DISPLAY_FIX_SUMMARY.md (Overview)"
echo "  - FIX_FOOD_DISPLAY.md (Detailed guide)"
echo "  - database/MIGRATION_FOOD_LOGS.sql (Migration SQL)"
echo ""
echo "🔍 DEBUGGING:"
echo "  - Check console for [useNutrition] logs"
echo "  - Verify food_logs table in Supabase dashboard"
echo "  - Check meal_type values are lowercase"
echo ""
echo "✅ WHAT WAS FIXED:"
echo "  ✓ Enhanced FoodLog TypeScript interface"
echo "  ✓ Added query logging for debugging"
echo "  ✓ Improved display fallback logic"
echo "  ✓ Created database migration for missing columns"
echo ""
